
@startuml LoginActivity
start
:Afficher le formulaire de connexion;
:Remplir les informations d'identification;
if (Identifiants valides ?) then (oui)
    :Authentifier l'utilisateur;
    :Afficher le tableau de bord;
else (non)
    :Afficher message d'erreur;
endif
stop
@enduml