//Ce code est une description de diagramme de séquence en utilisant le langage PlantUML. Il montre comment un utilisateur interagit avec le Service Mémoire pour ajouter un mémoire, en illustrant les étapes principales d'un processus d'ajout de mémoire dans un système de gestion de mémoire

@startuml
actor Administrateur
actor Utilisateur
participant "Service Mémoire" as ServiceMemoire
participant "Service Utilisateur" as ServiceUtilisateur
participant "Base de données" as DB

== Gestion des Utilisateurs ==
Administrateur -> ServiceUtilisateur : Créer un utilisateur
ServiceUtilisateur -> DB : Ajouter l'utilisateur avec rôle
DB --> ServiceUtilisateur : Confirmation
ServiceUtilisateur --> Administrateur : Utilisateur ajouté avec succès

Administrateur -> ServiceUtilisateur : Supprimer un utilisateur
ServiceUtilisateur -> DB : Supprimer les informations de l'utilisateur
DB --> ServiceUtilisateur : Confirmation
ServiceUtilisateur --> Administrateur : Utilisateur supprimé avec succès

== Gestion des Mémoires ==
Utilisateur -> ServiceMemoire : Demande d'ajout de mémoire
ServiceMemoire -> DB : Enregistre le mémoire
DB --> ServiceMemoire : Confirmation
ServiceMemoire --> Utilisateur : Mémoire ajoutée avec succès

Utilisateur -> ServiceMemoire : Rechercher un mémoire
ServiceMemoire -> DB : Requête de recherche
DB --> ServiceMemoire : Résultats de recherche
ServiceMemoire --> Utilisateur : Affiche les résultats

Utilisateur -> ServiceMemoire : Modifier un mémoire
ServiceMemoire -> DB : Mettre à jour les informations du mémoire
DB --> ServiceMemoire : Confirmation de la mise à jour
ServiceMemoire --> Utilisateur : Mémoire modifiée avec succès

Utilisateur -> ServiceMemoire : Supprimer un mémoire
ServiceMemoire -> DB : Supprimer le mémoire
DB --> ServiceMemoire : Confirmation de suppression
ServiceMemoire --> Utilisateur : Mémoire supprimée avec succès
@enduml
